title: Our Earth
description: Visualizing esoteric atmospheric energy
baseurl: "OurEarth" 
url: "https://RocBoi.github.io" # replace with your actual GitHub Pages URL
theme: minima
markdown: kramdown
